[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.16" 
eth-rpc-url = "https://mainnet.infura.io/v3/9b775ea28ddc472cb1ed7968f67a0df8"
gas_reports = ["*"]
via_ir = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }